var json_PovosMonitorados_12 = {
"type": "FeatureCollection",
"name": "PovosMonitorados_12",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Registro Nº": "51", "Nome": "Massaco", "Situação": "Isolados", "Etnia": "Siriono", "Língua": null }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -62.4, -12.78 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "41", "Nome": "Araribóia", "Situação": "Isolados", "Etnia": "Awa Guajá", "Língua": null }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -46.42, -5.21 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "33", "Nome": "Mashko do Rio Iaco", "Situação": "Isolados", "Etnia": "Mashko Piro", "Língua": null }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -70.44, -10.87 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "71", "Nome": "Mashko do Rio Chandless", "Situação": "Isolados", "Etnia": "Mashko Piro", "Língua": null }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -70.45, -10.47 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "16", "Nome": "Rio Itaquaí", "Situação": "Isolados", "Etnia": "Desconhecida", "Língua": null }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -70.5, -6.4 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "21", "Nome": "Igarapé Lambança", "Situação": "Isolados", "Etnia": "Korubo", "Língua": null }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -70.03, -4.95 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "25", "Nome": "Rio Quixito", "Situação": "Isolados", "Etnia": "Desconhecida", "Língua": "Pano" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -71.4, -5.04 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "91", "Nome": "Igarapé São José", "Situação": "Isolados", "Etnia": "Desconhecida", "Língua": null }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -70.33, -6.06 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "23", "Nome": "Rio Coari", "Situação": "Recente Contato", "Etnia": "Korubo", "Língua": null }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -70.9, -5.55 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "17", "Nome": "Igarapé Urucubaca", "Situação": "Recente Contato", "Etnia": "Tsohom Djapa", "Língua": "Katukina" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -69.46, -5.82 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "76", "Nome": "Serra da Estrutura", "Situação": "Isolados", "Etnia": "Moxihatëtëma", "Língua": "Yanomami" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -63.54, 3.24 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "39", "Nome": "Igarapés Presídio e Juriti", "Situação": "Isolados", "Etnia": "Awa Guajá", "Língua": null }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -46.31, -3.77 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "7", "Nome": "Pirititi", "Situação": "Isolados", "Etnia": "Pirititi", "Língua": null }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -60.37, -0.07 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "52", "Nome": "Akunt´su do Vale do rio Omerê", "Situação": "Recente Contato", "Etnia": "Akunt´su", "Língua": "Tupari" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -61.1, -12.8 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "62", "Nome": "Kanoe do Vale do rio Omerê", "Situação": "Recente Contato", "Etnia": "Kanoe", "Língua": "Kanoe" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -61.1, -12.8 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "53", "Nome": "Tanaru", "Situação": "Isolados", "Etnia": "Desconhecida", "Língua": null }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -61.35, -12.66 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "55", "Nome": "Piripikura", "Situação": "Isolados", "Etnia": "Desconhecida", "Língua": "Tupi Kawahiva" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -60.83, -9.69 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "59", "Nome": "Kawahiva do Rio Pardo", "Situação": "Isolados", "Etnia": "Desconhecida", "Língua": "Tupi Kawahiva" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -59.91, -8.99 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "15", "Nome": "Igarapé Nauá", "Situação": "Isolados", "Etnia": "Desconhecida", "Língua": null }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -70.1, -6.33 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "116", "Nome": "Mashko do Rio Envira", "Situação": "Isolados", "Etnia": "Mashko Piro", "Língua": null }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -71.98, -9.96 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "31", "Nome": "Riozinho do Alto Envira", "Situação": "Isolados", "Etnia": "Desconhecida", "Língua": null }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -71.21, -9.92 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "32", "Nome": "Rio Jaminawa", "Situação": "Isolados", "Etnia": "Desconhecida", "Língua": null }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -71.23, -9.74 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "30", "Nome": "Xinane e Igarapé do Douro", "Situação": "Recente Contato", "Etnia": "Tsapanawa", "Língua": "Pano" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -71.87, -9.88 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "115", "Nome": "Alto Rio Humaitá", "Situação": "Isolados", "Etnia": "Desconhecida", "Língua": null }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -71.55, -9.58 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "13", "Nome": "Hi-Merimã", "Situação": "Isolados", "Etnia": "Hi-merimã", "Língua": "Arawá" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -65.73, -6.89 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "69", "Nome": "Zuruaha", "Situação": "Recente Contato", "Etnia": "Zuruaha", "Língua": "Arawá" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -66.39, -6.91 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "38", "Nome": "Zo´é", "Situação": "Recente Contato", "Etnia": "Zo´é", "Língua": "Tupi-Guarani" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -55.83, -0.33 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "18", "Nome": "Igarapé Alerta", "Situação": "Isolados", "Etnia": "Desconhecida", "Língua": null }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -70.13, -5.55 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "19", "Nome": "Igarapé Inferno", "Situação": "Isolados", "Etnia": "Korubo", "Língua": null }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -69.88, -5.14 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "48", "Nome": "Cautário", "Situação": "Isolados", "Etnia": "Yrapararikuara", "Língua": null }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -63.59, -11.62 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "49", "Nome": "Bananeira", "Situação": "Isolados", "Etnia": "Yrapararikuara", "Língua": null }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -63.66, -11.27 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "50", "Nome": "Kawahiva do rio Muqui", "Situação": "Isolados", "Etnia": "Jururei", "Língua": null }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -62.56, -11.45 ] ] } },
{ "type": "Feature", "properties": { "Registro Nº": "90", "Nome": "Rio Esquerdo", "Situação": "Isolados", "Etnia": "Desconhecida", "Língua": "Pano" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -71.870610950906709, -5.111740113737109 ] ] } }
]
}
